### ISSUE TITLE
Login is not working properly

### ISSUE THREAD

**Issue by irajghayoumian** [soroushchehresa/clubhouse-unfollowers#2]
Hello again
I enter the number without spaces
https://streamable.com/0tvask
Check the link above ... (The video is from your site)
thank you 🌹

**Comment by soroushchehresa** [comment]
@irajghayoumian Hello, I think this issue is related to the Clubhouse server! Please try 0912 instead of 912 and let me know if worked.

**Comment by soroushchehresa** [comment]
@irajghayoumian Hello again, I haven't tested this app in android web browsers so far. 
**Please try from desktop or Safari.**

**Comment by irajghayoumian** [comment]
My friend, I tested it on iPhone and it sends the code
Thank you for taking the time to create this site
