### ISSUE TITLE
Not Accurate

### ISSUE THREAD

**Issue by starsorb** [soroushchehresa/clubhouse-unfollowers#3]
I tried to login today and found out the list not accurate, listing as unfollower but after I checked every account most of them or close to 95% still follow me, can you check this error

**Comment by soroushchehresa** [comment]
@starsorb This app is for unfollowing people who don't follow you, not for people who followed you.

**Comment by starsorb** [comment]
What I mean, you listed as unfollower but after checking every account actually they still follow you not as unfollower

**Comment by soroushchehresa** [comment]
@starsorb What's your web browser?

**Comment by starsorb** [comment]
Safari

**Comment by soroushchehresa** [comment]
@starsorb 
I tested this application again on my iPhone just now and it works properly!
If you have some trouble please send me a video of what you expecting that not properly working.

**Comment by irajghayoumian** [comment]
![IMG_20210402_144018_939](https://user-images.githubusercontent.com/81629608/113406856-7375c000-93c1-11eb-864e-f322ed58497d.jpg)

I researched and found out that this project only sends code on the iPhone

Please edit the project

**Comment by starsorb** [comment]
i can not semd video here but for example the first list Arun Chandran listed does not follow me, but I checked the account he still follow me and the same result with other account name list when I chacked their account directly

![7BC94E66-46C0-4A27-867E-66E5F3E97F79](https://user-images.githubusercontent.com/81785375/113417254-9621cc00-93f5-11eb-9afc-6af7f0f5bb77.png)u
![Uploading 9405874B-27E9-41A3-A62A-F8D0E9023A3D.png…]


![DB83DD44-5ABE-43C9-81B0-EF9351E82D1E](https://user-images.githubusercontent.com/81785375/113417247-928e4500-93f5-11eb-820e-aa91b93182a9.png)

**Comment by soroushchehresa** [comment]
This issue is related to the Clubhouse server.
